- name: install haproxy
  apt:
    name:
      - haproxy
      - hatop
      - haveged
    state: present

- name: create directory for error files
  file:
    state: directory
    path: /etc/haproxy/errors/
    owner: www-data
    group: www-data
    mode: 0750

- name: template /etc/haproxy/haproxy.cfg
  template:
    src: "templates/etc/haproxy/haproxy.cfg.j2"
    dest: "/etc/haproxy/haproxy.cfg"
    owner: root
    group: root
    mode: 0600
  notify: restart haproxy

- name: create haproxy directories
  file:
    state: directory
    path: "/var/lib/haproxy/{{ haproxy_directory }}"
    owner: haproxy
    group: haproxy
    mode: 0700
  with_items:
    - ssl
    - errors
  loop_control:
    loop_var: haproxy_directory

- name: manage error files
  template:
    src: "templates/etc/haproxy/errors/{{ haproxy_errorfile }}.http.j2"
    dest: "/etc/haproxy/errors/{{ haproxy_errorfile }}.http"
    owner: www-data
    group: www-data
    mode: 0640
  with_items: "{{ haproxy_errorfiles }}"
  loop_control:
    loop_var: haproxy_errorfile
  when: haproxy_errorfiles != []
