- name: validate haproxy.cfg
  command: haproxy -f /etc/haproxy/haproxy.cfg -c -q
  listen: restart haproxy

- name: restart haproxy
  systemd:
    name: haproxy
    state: restarted
    enabled: True
  listen: restart haproxy

