- name: create haproxy ssl directory
  file:
    state: directory
    path: /var/lib/haproxy/ssl
    owner: haproxy
    group: haproxy
    mode: 0700

# TODO bugs around, says it cant find the module, https://docs.ansible.com/ansible/devel/modules/openssl_dhparam_module.html
#- name: create openssl dhparam (may take a while)
#  openssl_dhparam:
#    path: /var/lib/haproxy/ssl/dh4096.pem
#    size: 4096
- name: create openssl dhparam (may take a while - could be an hour or so)
  command: "openssl dhparam -outform PEM -out /var/lib/haproxy/ssl/dh{{ haproxy_dhparam_size }}.pem {{ haproxy_dhparam_size }}"
  args:
    creates: "/var/lib/haproxy/ssl/dh{{ haproxy_dhparam_size }}.pem"
  no_log: yes

- name: set permissions on dhparam
  file:
    state: file
    path: "/var/lib/haproxy/ssl/dh{{ haproxy_dhparam_size }}.pem"
    owner: haproxy
    group: haproxy
    mode: 0400

- name: load openssl dhparam into a variable
  command: "cat /var/lib/haproxy/ssl/dh{{ haproxy_dhparam_size }}.pem"
  register: haproxy_ssl_dhparam
  no_log: yes

- name: template ssl certificate chain file
  template:
    src: "var/lib/haproxy/ssl/certificate-template.pem.j2"
    dest: "/var/lib/haproxy/ssl/{{ haproxy_certificate_filename }}.pem"
    owner: haproxy
    group: haproxy
    mode: 0400
  notify: restart haproxy
  no_log: yes

- name: template /etc/haproxy/haproxy.cfg
  template:
    src: "etc/haproxy/haproxy.cfg.j2"
    dest: "/etc/haproxy/haproxy.cfg"
    owner: root
    group: root
    mode: 0600
    validate: haproxy -f %s -c -q
  notify: restart haproxy
